portfolio_web/about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about_me, name='about'),
    path('edit/', views.edit_about_me, name='edit_about'),
]

portfolio_web/portfolio_web/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('urls/', include('blogpost.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("weather/", include("weather_app.urls")),
    path('api/', include('post_api.urls')),
    path('', include('home_slider.urls')),
    path('about/',include("about.urls"))
]

portfolio_web/todo_app/urls.py
from django.urls import path
from .views import todo_list, todo_create, todo_update, todo_delete

app_name = 'todo'

urlpatterns = [
    path('', todo_list, name='list'),
    path('create/', todo_create, name='create'),
    path('update/<int:pk>/', todo_update, name='update'),
    path('delete/<int:pk>/', todo_delete, name='delete'),
]

portfolio_web/todo_app/models.py
from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

portfolio_web/todo_app/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'description']

portfolio_web/todo_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Todo
from .forms import TodoForm

def todo_list(request):
    todos = Todo.objects.all()
    return render(request, 'todo/list.html', {'todos': todos})

def todo_create(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todo:list')
    else:
        form = TodoForm()
    return render(request, 'todo/create.html', {'form': form})

def todo_update(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect('todo:list')
    else:
        form = TodoForm(instance=todo)
    return render(request, 'todo/update.html', {'form': form, 'todo': todo})

def todo_delete(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    if request.method == 'POST':
        todo.delete()
        return redirect('todo:list')
    return render(request, 'todo_app/delete.html', {'todo': todo})

portfolio_web/templates/todo_app/create.html
<h1>Create New TODO</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create</button>
</form>

portfolio_web/templates/todo_app/delete.html
<h1>Delete TODO</h1>
<p>Are you sure you want to delete "{{ todo.title }}"?</p>
<form method="POST">
  {% csrf_token %}
  <button type="submit">Delete</button>
</form>

portfolio_web/templates/todo_app/list.html
{% extends "base.html" %}

<h1>TODO List</h1>
<ul>
  {% for todo in todos %}
    <li>
      {{ todo.title }}
      <a href="{% url 'todo:update' pk=todo.pk %}">Edit</a>
      <a href="{% url 'todo:delete' pk=todo.pk %}">Delete</a>
    </li>
  {% empty %}
    <li>No todos found.</li>
  {% endfor %}
</ul>
<a href="{% url 'todo:create' %}">Create New TODO</a>

portfolio_web/templates/todo_app/update.html
<h1>Edit TODO</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Update</button>
</form>